name = "Cascadia"
uuid = "54eefc05-d75b-58de-a785-1a3403f0919f"
version = "1.0.2"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"

[compat]
AbstractTrees = "0.2, 0.3, 0.4"
Gumbo = "0.5, 0.7, 0.8"
julia = "0.7, 1"

[extras]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JSON", "Test"]
